name:                marginal
version:             0.0.1.0
github:              "jhmcstanton/marginal"
license:             BSD3
author:              "Jim McStanton"
maintainer:          "jim@jhmcstanton.com"
copyright:           "2019 Jim McStanton"

extra-source-files:
- README.md
- ChangeLog.md
- src/Marginal/Parse/OnePhase/Lexer.x
- src/Marginal/Parse/TwoPhase/Lexer.x

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/jhmcstanton/marginal#readme>

dependencies:
- base               >= 4.7 && < 5
- array              >= 0.5.3.0
- bytestring         >= 0.10.8.2

library:
  source-dirs: src
  build-tools:
  - alex
  - happy
  exposed-modules:
  - Marginal.Parse.OnePhase.Lexer
  - Marginal.Parse.TwoPhase.Lexer

executables:
  marginal-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - marginal

tests:
  marginal-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - marginal
